---
- hosts: all
  become: true
  become_user: ansadmin
  vars:
   tomcat_url: https://mirrors.gigenet.com/apache/tomcat/tomcat-7/v7.0.105/bin/apache-tomcat-7.0.105.tar.gz 
   tomcat_version: 7.0.105

  tasks:
   - name: Install Java
     yum:
      name: java
      state: latest

   - name: Create the tomcat directory
     file: 
      path: /home/ansadmin/tomcat
      state: directory
      mode: '0755'
  
   - name: Download the tomcat binaries
     get_url:
      url: "{{ tomcat_url }}"
      dest: /home/ansadmin/tomcat
      mode: '0755' 

   - name: Untar the tomcat binary 
     unarchive:
      src: /home/ansadmin/tomcat/apache-tomcat-{{ tomcat_version }}.tar.gz
      dest: /home/ansadmin/
      remote_src: yes

   - name: start the tomcat service
     command: nohup /home/ansadmin/apache-tomcat-{{ tomcat_version }}/bin/startup.sh
