---
- hosts: all
  become: true
  become_user: ansadmin
  
  tasks:
   - name: Install Java
     yum:
      name: java
      state: latest
   - name: Create the tomcat directory
     file: 
      path: /home/ansadmin/tomcat
      state: directory
      mode: '0755'
  
   - name: Download the tomcat binaries
     get_url:
      url: http://www.gtlib.gatech.edu/pub/apache/tomcat/tomcat-8/v8.5.57/bin/apache-tomcat-8.5.57.tar.gz 
      dest: /home/ansadmin/tomcat
      mode: '0755' 

   - name: Untar the tomcat binary 
     unarchive:
      src: /home/ansadmin/tomcat/apache-tomcat-8.5.57.tar.gz
      dest: /home/ansadmin/
      remote_src: yes

   - name: Change file permission of tomcat
     file:
      path: /home/ansadmin/apache-tomcat-8.5.57
      state: directory
      mode: 0755
      recurse: true

   - name: start the tomcat service
     command: nohup /home/ansadmin/apache-tomcat-8.5.57/bin/startup.sh
